CREATE DATABASE enddate CHARACTER SET utf8 COLLATE utf8_general_ci;
USE enddate;

CREATE TABLE dates (
  id int(11) NOT NULL AUTO_INCREMENT,
	datedata int(11) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=5 ;

INSERT INTO dates (id, datedata) VALUES
(1, 1234567);